"""init schema

Revision ID: 7f9cec9abb5c
Revises: 
Create Date: 2026-04-26 20:46:11.399023

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f9cec9abb5c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('season',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('seed', sa.Integer(), nullable=False),
    sa.Column('user_team_id', sa.Integer(), nullable=True),
    sa.Column('current_matchday', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('team',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('abbreviation', sa.String(length=3), nullable=False),
    sa.ForeignKeyConstraint(['season_id'], ['season.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_team_season_id'), 'team', ['season_id'], unique=False)
    op.create_table('game',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('matchday', sa.Integer(), nullable=False),
    sa.Column('home_team_id', sa.Integer(), nullable=False),
    sa.Column('away_team_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('home_score', sa.Integer(), nullable=True),
    sa.Column('away_score', sa.Integer(), nullable=True),
    sa.Column('home_shots', sa.Integer(), nullable=True),
    sa.Column('away_shots', sa.Integer(), nullable=True),
    sa.Column('result_type', sa.String(length=3), nullable=True),
    sa.Column('seed', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['away_team_id'], ['team.id'], ),
    sa.ForeignKeyConstraint(['home_team_id'], ['team.id'], ),
    sa.ForeignKeyConstraint(['season_id'], ['season.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_game_matchday'), 'game', ['matchday'], unique=False)
    op.create_index(op.f('ix_game_season_id'), 'game', ['season_id'], unique=False)
    op.create_table('goalie',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('reflexes', sa.Integer(), nullable=False),
    sa.Column('positioning', sa.Integer(), nullable=False),
    sa.Column('rebound_control', sa.Integer(), nullable=False),
    sa.Column('puck_handling', sa.Integer(), nullable=False),
    sa.Column('mental', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_goalie_team_id'), 'goalie', ['team_id'], unique=False)
    op.create_table('skater',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('position', sa.String(length=2), nullable=False),
    sa.Column('skating', sa.Integer(), nullable=False),
    sa.Column('shooting', sa.Integer(), nullable=False),
    sa.Column('passing', sa.Integer(), nullable=False),
    sa.Column('defense', sa.Integer(), nullable=False),
    sa.Column('physical', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skater_team_id'), 'skater', ['team_id'], unique=False)
    op.create_table('standing',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('games_played', sa.Integer(), nullable=False),
    sa.Column('wins', sa.Integer(), nullable=False),
    sa.Column('losses', sa.Integer(), nullable=False),
    sa.Column('ot_losses', sa.Integer(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('goals_for', sa.Integer(), nullable=False),
    sa.Column('goals_against', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['season_id'], ['season.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id', 'season_id')
    )
    op.create_index(op.f('ix_standing_season_id'), 'standing', ['season_id'], unique=False)
    op.create_index(op.f('ix_standing_team_id'), 'standing', ['team_id'], unique=False)
    op.create_table('game_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('tick', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=8), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('primary_skater_id', sa.Integer(), nullable=True),
    sa.Column('assist1_id', sa.Integer(), nullable=True),
    sa.Column('assist2_id', sa.Integer(), nullable=True),
    sa.Column('goalie_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['assist1_id'], ['skater.id'], ),
    sa.ForeignKeyConstraint(['assist2_id'], ['skater.id'], ),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['goalie_id'], ['goalie.id'], ),
    sa.ForeignKeyConstraint(['primary_skater_id'], ['skater.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_game_event_game_id'), 'game_event', ['game_id'], unique=False)
    op.create_table('goalie_game_stat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('goalie_id', sa.Integer(), nullable=False),
    sa.Column('shots_against', sa.Integer(), nullable=False),
    sa.Column('saves', sa.Integer(), nullable=False),
    sa.Column('goals_against', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['goalie_id'], ['goalie.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_goalie_game_stat_game_id'), 'goalie_game_stat', ['game_id'], unique=False)
    op.create_index(op.f('ix_goalie_game_stat_goalie_id'), 'goalie_game_stat', ['goalie_id'], unique=False)
    op.create_table('lineup',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('line1_lw_id', sa.Integer(), nullable=False),
    sa.Column('line1_c_id', sa.Integer(), nullable=False),
    sa.Column('line1_rw_id', sa.Integer(), nullable=False),
    sa.Column('line2_lw_id', sa.Integer(), nullable=False),
    sa.Column('line2_c_id', sa.Integer(), nullable=False),
    sa.Column('line2_rw_id', sa.Integer(), nullable=False),
    sa.Column('line3_lw_id', sa.Integer(), nullable=False),
    sa.Column('line3_c_id', sa.Integer(), nullable=False),
    sa.Column('line3_rw_id', sa.Integer(), nullable=False),
    sa.Column('line4_lw_id', sa.Integer(), nullable=False),
    sa.Column('line4_c_id', sa.Integer(), nullable=False),
    sa.Column('line4_rw_id', sa.Integer(), nullable=False),
    sa.Column('pair1_ld_id', sa.Integer(), nullable=False),
    sa.Column('pair1_rd_id', sa.Integer(), nullable=False),
    sa.Column('pair2_ld_id', sa.Integer(), nullable=False),
    sa.Column('pair2_rd_id', sa.Integer(), nullable=False),
    sa.Column('pair3_ld_id', sa.Integer(), nullable=False),
    sa.Column('pair3_rd_id', sa.Integer(), nullable=False),
    sa.Column('starting_goalie_id', sa.Integer(), nullable=False),
    sa.Column('backup_goalie_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['backup_goalie_id'], ['goalie.id'], ),
    sa.ForeignKeyConstraint(['line1_c_id'], ['skater.id'], ),
    sa.ForeignKeyConstraint(['line1_lw_id'], ['skater.id'], ),
    sa.ForeignKeyConstraint(['line1_rw_id'], ['skater.id'], ),
    sa.ForeignKeyConstraint(['line2_c_id'], ['skater.id'], ),
    sa.ForeignKeyConstraint(['line2_lw_id'], ['skater.id'], ),
    sa.ForeignKeyConstraint(['line2_rw_id'], ['skater.id'], ),
    sa.ForeignKeyConstraint(['line3_c_id'], ['skater.id'], ),
    sa.ForeignKeyConstraint(['line3_lw_id'], ['skater.id'], ),
    sa.ForeignKeyConstraint(['line3_rw_id'], ['skater.id'], ),
    sa.ForeignKeyConstraint(['line4_c_id'], ['skater.id'], ),
    sa.ForeignKeyConstraint(['line4_lw_id'], ['skater.id'], ),
    sa.ForeignKeyConstraint(['line4_rw_id'], ['skater.id'], ),
    sa.ForeignKeyConstraint(['pair1_ld_id'], ['skater.id'], ),
    sa.ForeignKeyConstraint(['pair1_rd_id'], ['skater.id'], ),
    sa.ForeignKeyConstraint(['pair2_ld_id'], ['skater.id'], ),
    sa.ForeignKeyConstraint(['pair2_rd_id'], ['skater.id'], ),
    sa.ForeignKeyConstraint(['pair3_ld_id'], ['skater.id'], ),
    sa.ForeignKeyConstraint(['pair3_rd_id'], ['skater.id'], ),
    sa.ForeignKeyConstraint(['starting_goalie_id'], ['goalie.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id')
    )
    op.create_table('skater_game_stat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('skater_id', sa.Integer(), nullable=False),
    sa.Column('goals', sa.Integer(), nullable=False),
    sa.Column('assists', sa.Integer(), nullable=False),
    sa.Column('shots', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skater_id'], ['skater.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skater_game_stat_game_id'), 'skater_game_stat', ['game_id'], unique=False)
    op.create_index(op.f('ix_skater_game_stat_skater_id'), 'skater_game_stat', ['skater_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_skater_game_stat_skater_id'), table_name='skater_game_stat')
    op.drop_index(op.f('ix_skater_game_stat_game_id'), table_name='skater_game_stat')
    op.drop_table('skater_game_stat')
    op.drop_table('lineup')
    op.drop_index(op.f('ix_goalie_game_stat_goalie_id'), table_name='goalie_game_stat')
    op.drop_index(op.f('ix_goalie_game_stat_game_id'), table_name='goalie_game_stat')
    op.drop_table('goalie_game_stat')
    op.drop_index(op.f('ix_game_event_game_id'), table_name='game_event')
    op.drop_table('game_event')
    op.drop_index(op.f('ix_standing_team_id'), table_name='standing')
    op.drop_index(op.f('ix_standing_season_id'), table_name='standing')
    op.drop_table('standing')
    op.drop_index(op.f('ix_skater_team_id'), table_name='skater')
    op.drop_table('skater')
    op.drop_index(op.f('ix_goalie_team_id'), table_name='goalie')
    op.drop_table('goalie')
    op.drop_index(op.f('ix_game_season_id'), table_name='game')
    op.drop_index(op.f('ix_game_matchday'), table_name='game')
    op.drop_table('game')
    op.drop_index(op.f('ix_team_season_id'), table_name='team')
    op.drop_table('team')
    op.drop_table('season')
    # ### end Alembic commands ###
