/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StatsRouteImport } from './routes/stats'
import { Route as StandingsRouteImport } from './routes/standings'
import { Route as SeasonCompleteRouteImport } from './routes/season-complete'
import { Route as ScheduleRouteImport } from './routes/schedule'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TeamTeamIdRouteImport } from './routes/team.$teamId'
import { Route as GameGameIdRouteImport } from './routes/game.$gameId'
import { Route as TeamTeamIdLineupRouteImport } from './routes/team.$teamId.lineup'
import { Route as PlayerSkaterIdRouteImport } from './routes/player.skater.$id'
import { Route as PlayerGoalieIdRouteImport } from './routes/player.goalie.$id'

const StatsRoute = StatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const StandingsRoute = StandingsRouteImport.update({
  id: '/standings',
  path: '/standings',
  getParentRoute: () => rootRouteImport,
} as any)
const SeasonCompleteRoute = SeasonCompleteRouteImport.update({
  id: '/season-complete',
  path: '/season-complete',
  getParentRoute: () => rootRouteImport,
} as any)
const ScheduleRoute = ScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamTeamIdRoute = TeamTeamIdRouteImport.update({
  id: '/team/$teamId',
  path: '/team/$teamId',
  getParentRoute: () => rootRouteImport,
} as any)
const GameGameIdRoute = GameGameIdRouteImport.update({
  id: '/game/$gameId',
  path: '/game/$gameId',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamTeamIdLineupRoute = TeamTeamIdLineupRouteImport.update({
  id: '/lineup',
  path: '/lineup',
  getParentRoute: () => TeamTeamIdRoute,
} as any)
const PlayerSkaterIdRoute = PlayerSkaterIdRouteImport.update({
  id: '/player/skater/$id',
  path: '/player/skater/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayerGoalieIdRoute = PlayerGoalieIdRouteImport.update({
  id: '/player/goalie/$id',
  path: '/player/goalie/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/schedule': typeof ScheduleRoute
  '/season-complete': typeof SeasonCompleteRoute
  '/standings': typeof StandingsRoute
  '/stats': typeof StatsRoute
  '/game/$gameId': typeof GameGameIdRoute
  '/team/$teamId': typeof TeamTeamIdRouteWithChildren
  '/player/goalie/$id': typeof PlayerGoalieIdRoute
  '/player/skater/$id': typeof PlayerSkaterIdRoute
  '/team/$teamId/lineup': typeof TeamTeamIdLineupRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/schedule': typeof ScheduleRoute
  '/season-complete': typeof SeasonCompleteRoute
  '/standings': typeof StandingsRoute
  '/stats': typeof StatsRoute
  '/game/$gameId': typeof GameGameIdRoute
  '/team/$teamId': typeof TeamTeamIdRouteWithChildren
  '/player/goalie/$id': typeof PlayerGoalieIdRoute
  '/player/skater/$id': typeof PlayerSkaterIdRoute
  '/team/$teamId/lineup': typeof TeamTeamIdLineupRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/schedule': typeof ScheduleRoute
  '/season-complete': typeof SeasonCompleteRoute
  '/standings': typeof StandingsRoute
  '/stats': typeof StatsRoute
  '/game/$gameId': typeof GameGameIdRoute
  '/team/$teamId': typeof TeamTeamIdRouteWithChildren
  '/player/goalie/$id': typeof PlayerGoalieIdRoute
  '/player/skater/$id': typeof PlayerSkaterIdRoute
  '/team/$teamId/lineup': typeof TeamTeamIdLineupRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/schedule'
    | '/season-complete'
    | '/standings'
    | '/stats'
    | '/game/$gameId'
    | '/team/$teamId'
    | '/player/goalie/$id'
    | '/player/skater/$id'
    | '/team/$teamId/lineup'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/schedule'
    | '/season-complete'
    | '/standings'
    | '/stats'
    | '/game/$gameId'
    | '/team/$teamId'
    | '/player/goalie/$id'
    | '/player/skater/$id'
    | '/team/$teamId/lineup'
  id:
    | '__root__'
    | '/'
    | '/schedule'
    | '/season-complete'
    | '/standings'
    | '/stats'
    | '/game/$gameId'
    | '/team/$teamId'
    | '/player/goalie/$id'
    | '/player/skater/$id'
    | '/team/$teamId/lineup'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ScheduleRoute: typeof ScheduleRoute
  SeasonCompleteRoute: typeof SeasonCompleteRoute
  StandingsRoute: typeof StandingsRoute
  StatsRoute: typeof StatsRoute
  GameGameIdRoute: typeof GameGameIdRoute
  TeamTeamIdRoute: typeof TeamTeamIdRouteWithChildren
  PlayerGoalieIdRoute: typeof PlayerGoalieIdRoute
  PlayerSkaterIdRoute: typeof PlayerSkaterIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/stats': {
      id: '/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/standings': {
      id: '/standings'
      path: '/standings'
      fullPath: '/standings'
      preLoaderRoute: typeof StandingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/season-complete': {
      id: '/season-complete'
      path: '/season-complete'
      fullPath: '/season-complete'
      preLoaderRoute: typeof SeasonCompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schedule': {
      id: '/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof ScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team/$teamId': {
      id: '/team/$teamId'
      path: '/team/$teamId'
      fullPath: '/team/$teamId'
      preLoaderRoute: typeof TeamTeamIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game/$gameId': {
      id: '/game/$gameId'
      path: '/game/$gameId'
      fullPath: '/game/$gameId'
      preLoaderRoute: typeof GameGameIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team/$teamId/lineup': {
      id: '/team/$teamId/lineup'
      path: '/lineup'
      fullPath: '/team/$teamId/lineup'
      preLoaderRoute: typeof TeamTeamIdLineupRouteImport
      parentRoute: typeof TeamTeamIdRoute
    }
    '/player/skater/$id': {
      id: '/player/skater/$id'
      path: '/player/skater/$id'
      fullPath: '/player/skater/$id'
      preLoaderRoute: typeof PlayerSkaterIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/player/goalie/$id': {
      id: '/player/goalie/$id'
      path: '/player/goalie/$id'
      fullPath: '/player/goalie/$id'
      preLoaderRoute: typeof PlayerGoalieIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface TeamTeamIdRouteChildren {
  TeamTeamIdLineupRoute: typeof TeamTeamIdLineupRoute
}

const TeamTeamIdRouteChildren: TeamTeamIdRouteChildren = {
  TeamTeamIdLineupRoute: TeamTeamIdLineupRoute,
}

const TeamTeamIdRouteWithChildren = TeamTeamIdRoute._addFileChildren(
  TeamTeamIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ScheduleRoute: ScheduleRoute,
  SeasonCompleteRoute: SeasonCompleteRoute,
  StandingsRoute: StandingsRoute,
  StatsRoute: StatsRoute,
  GameGameIdRoute: GameGameIdRoute,
  TeamTeamIdRoute: TeamTeamIdRouteWithChildren,
  PlayerGoalieIdRoute: PlayerGoalieIdRoute,
  PlayerSkaterIdRoute: PlayerSkaterIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
