/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TradesRouteImport } from './routes/trades'
import { Route as StatsRouteImport } from './routes/stats'
import { Route as StandingsRouteImport } from './routes/standings'
import { Route as SeasonCompleteRouteImport } from './routes/season-complete'
import { Route as ScheduleRouteImport } from './routes/schedule'
import { Route as PlayoffsRouteImport } from './routes/playoffs'
import { Route as FreeAgentsRouteImport } from './routes/free-agents'
import { Route as DevelopmentSummaryRouteImport } from './routes/development-summary'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ManagerIndexRouteImport } from './routes/manager.index'
import { Route as TeamTeamIdRouteImport } from './routes/team.$teamId'
import { Route as ManagerCreateRouteImport } from './routes/manager.create'
import { Route as ManagerChooseTeamRouteImport } from './routes/manager.choose-team'
import { Route as GameGameIdRouteImport } from './routes/game.$gameId'
import { Route as GamePreviewGameIdRouteImport } from './routes/game-preview.$gameId'
import { Route as TeamTeamIdLineupRouteImport } from './routes/team.$teamId.lineup'
import { Route as PlayerSkaterIdRouteImport } from './routes/player.skater.$id'
import { Route as PlayerGoalieIdRouteImport } from './routes/player.goalie.$id'

const TradesRoute = TradesRouteImport.update({
  id: '/trades',
  path: '/trades',
  getParentRoute: () => rootRouteImport,
} as any)
const StatsRoute = StatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const StandingsRoute = StandingsRouteImport.update({
  id: '/standings',
  path: '/standings',
  getParentRoute: () => rootRouteImport,
} as any)
const SeasonCompleteRoute = SeasonCompleteRouteImport.update({
  id: '/season-complete',
  path: '/season-complete',
  getParentRoute: () => rootRouteImport,
} as any)
const ScheduleRoute = ScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayoffsRoute = PlayoffsRouteImport.update({
  id: '/playoffs',
  path: '/playoffs',
  getParentRoute: () => rootRouteImport,
} as any)
const FreeAgentsRoute = FreeAgentsRouteImport.update({
  id: '/free-agents',
  path: '/free-agents',
  getParentRoute: () => rootRouteImport,
} as any)
const DevelopmentSummaryRoute = DevelopmentSummaryRouteImport.update({
  id: '/development-summary',
  path: '/development-summary',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerIndexRoute = ManagerIndexRouteImport.update({
  id: '/manager/',
  path: '/manager/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamTeamIdRoute = TeamTeamIdRouteImport.update({
  id: '/team/$teamId',
  path: '/team/$teamId',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerCreateRoute = ManagerCreateRouteImport.update({
  id: '/manager/create',
  path: '/manager/create',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerChooseTeamRoute = ManagerChooseTeamRouteImport.update({
  id: '/manager/choose-team',
  path: '/manager/choose-team',
  getParentRoute: () => rootRouteImport,
} as any)
const GameGameIdRoute = GameGameIdRouteImport.update({
  id: '/game/$gameId',
  path: '/game/$gameId',
  getParentRoute: () => rootRouteImport,
} as any)
const GamePreviewGameIdRoute = GamePreviewGameIdRouteImport.update({
  id: '/game-preview/$gameId',
  path: '/game-preview/$gameId',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamTeamIdLineupRoute = TeamTeamIdLineupRouteImport.update({
  id: '/lineup',
  path: '/lineup',
  getParentRoute: () => TeamTeamIdRoute,
} as any)
const PlayerSkaterIdRoute = PlayerSkaterIdRouteImport.update({
  id: '/player/skater/$id',
  path: '/player/skater/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayerGoalieIdRoute = PlayerGoalieIdRouteImport.update({
  id: '/player/goalie/$id',
  path: '/player/goalie/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/development-summary': typeof DevelopmentSummaryRoute
  '/free-agents': typeof FreeAgentsRoute
  '/playoffs': typeof PlayoffsRoute
  '/schedule': typeof ScheduleRoute
  '/season-complete': typeof SeasonCompleteRoute
  '/standings': typeof StandingsRoute
  '/stats': typeof StatsRoute
  '/trades': typeof TradesRoute
  '/game-preview/$gameId': typeof GamePreviewGameIdRoute
  '/game/$gameId': typeof GameGameIdRoute
  '/manager/choose-team': typeof ManagerChooseTeamRoute
  '/manager/create': typeof ManagerCreateRoute
  '/team/$teamId': typeof TeamTeamIdRouteWithChildren
  '/manager/': typeof ManagerIndexRoute
  '/player/goalie/$id': typeof PlayerGoalieIdRoute
  '/player/skater/$id': typeof PlayerSkaterIdRoute
  '/team/$teamId/lineup': typeof TeamTeamIdLineupRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/development-summary': typeof DevelopmentSummaryRoute
  '/free-agents': typeof FreeAgentsRoute
  '/playoffs': typeof PlayoffsRoute
  '/schedule': typeof ScheduleRoute
  '/season-complete': typeof SeasonCompleteRoute
  '/standings': typeof StandingsRoute
  '/stats': typeof StatsRoute
  '/trades': typeof TradesRoute
  '/game-preview/$gameId': typeof GamePreviewGameIdRoute
  '/game/$gameId': typeof GameGameIdRoute
  '/manager/choose-team': typeof ManagerChooseTeamRoute
  '/manager/create': typeof ManagerCreateRoute
  '/team/$teamId': typeof TeamTeamIdRouteWithChildren
  '/manager': typeof ManagerIndexRoute
  '/player/goalie/$id': typeof PlayerGoalieIdRoute
  '/player/skater/$id': typeof PlayerSkaterIdRoute
  '/team/$teamId/lineup': typeof TeamTeamIdLineupRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/development-summary': typeof DevelopmentSummaryRoute
  '/free-agents': typeof FreeAgentsRoute
  '/playoffs': typeof PlayoffsRoute
  '/schedule': typeof ScheduleRoute
  '/season-complete': typeof SeasonCompleteRoute
  '/standings': typeof StandingsRoute
  '/stats': typeof StatsRoute
  '/trades': typeof TradesRoute
  '/game-preview/$gameId': typeof GamePreviewGameIdRoute
  '/game/$gameId': typeof GameGameIdRoute
  '/manager/choose-team': typeof ManagerChooseTeamRoute
  '/manager/create': typeof ManagerCreateRoute
  '/team/$teamId': typeof TeamTeamIdRouteWithChildren
  '/manager/': typeof ManagerIndexRoute
  '/player/goalie/$id': typeof PlayerGoalieIdRoute
  '/player/skater/$id': typeof PlayerSkaterIdRoute
  '/team/$teamId/lineup': typeof TeamTeamIdLineupRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/development-summary'
    | '/free-agents'
    | '/playoffs'
    | '/schedule'
    | '/season-complete'
    | '/standings'
    | '/stats'
    | '/trades'
    | '/game-preview/$gameId'
    | '/game/$gameId'
    | '/manager/choose-team'
    | '/manager/create'
    | '/team/$teamId'
    | '/manager/'
    | '/player/goalie/$id'
    | '/player/skater/$id'
    | '/team/$teamId/lineup'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/development-summary'
    | '/free-agents'
    | '/playoffs'
    | '/schedule'
    | '/season-complete'
    | '/standings'
    | '/stats'
    | '/trades'
    | '/game-preview/$gameId'
    | '/game/$gameId'
    | '/manager/choose-team'
    | '/manager/create'
    | '/team/$teamId'
    | '/manager'
    | '/player/goalie/$id'
    | '/player/skater/$id'
    | '/team/$teamId/lineup'
  id:
    | '__root__'
    | '/'
    | '/development-summary'
    | '/free-agents'
    | '/playoffs'
    | '/schedule'
    | '/season-complete'
    | '/standings'
    | '/stats'
    | '/trades'
    | '/game-preview/$gameId'
    | '/game/$gameId'
    | '/manager/choose-team'
    | '/manager/create'
    | '/team/$teamId'
    | '/manager/'
    | '/player/goalie/$id'
    | '/player/skater/$id'
    | '/team/$teamId/lineup'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DevelopmentSummaryRoute: typeof DevelopmentSummaryRoute
  FreeAgentsRoute: typeof FreeAgentsRoute
  PlayoffsRoute: typeof PlayoffsRoute
  ScheduleRoute: typeof ScheduleRoute
  SeasonCompleteRoute: typeof SeasonCompleteRoute
  StandingsRoute: typeof StandingsRoute
  StatsRoute: typeof StatsRoute
  TradesRoute: typeof TradesRoute
  GamePreviewGameIdRoute: typeof GamePreviewGameIdRoute
  GameGameIdRoute: typeof GameGameIdRoute
  ManagerChooseTeamRoute: typeof ManagerChooseTeamRoute
  ManagerCreateRoute: typeof ManagerCreateRoute
  TeamTeamIdRoute: typeof TeamTeamIdRouteWithChildren
  ManagerIndexRoute: typeof ManagerIndexRoute
  PlayerGoalieIdRoute: typeof PlayerGoalieIdRoute
  PlayerSkaterIdRoute: typeof PlayerSkaterIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trades': {
      id: '/trades'
      path: '/trades'
      fullPath: '/trades'
      preLoaderRoute: typeof TradesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stats': {
      id: '/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/standings': {
      id: '/standings'
      path: '/standings'
      fullPath: '/standings'
      preLoaderRoute: typeof StandingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/season-complete': {
      id: '/season-complete'
      path: '/season-complete'
      fullPath: '/season-complete'
      preLoaderRoute: typeof SeasonCompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schedule': {
      id: '/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof ScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playoffs': {
      id: '/playoffs'
      path: '/playoffs'
      fullPath: '/playoffs'
      preLoaderRoute: typeof PlayoffsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/free-agents': {
      id: '/free-agents'
      path: '/free-agents'
      fullPath: '/free-agents'
      preLoaderRoute: typeof FreeAgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/development-summary': {
      id: '/development-summary'
      path: '/development-summary'
      fullPath: '/development-summary'
      preLoaderRoute: typeof DevelopmentSummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager/': {
      id: '/manager/'
      path: '/manager'
      fullPath: '/manager/'
      preLoaderRoute: typeof ManagerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team/$teamId': {
      id: '/team/$teamId'
      path: '/team/$teamId'
      fullPath: '/team/$teamId'
      preLoaderRoute: typeof TeamTeamIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager/create': {
      id: '/manager/create'
      path: '/manager/create'
      fullPath: '/manager/create'
      preLoaderRoute: typeof ManagerCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager/choose-team': {
      id: '/manager/choose-team'
      path: '/manager/choose-team'
      fullPath: '/manager/choose-team'
      preLoaderRoute: typeof ManagerChooseTeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game/$gameId': {
      id: '/game/$gameId'
      path: '/game/$gameId'
      fullPath: '/game/$gameId'
      preLoaderRoute: typeof GameGameIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game-preview/$gameId': {
      id: '/game-preview/$gameId'
      path: '/game-preview/$gameId'
      fullPath: '/game-preview/$gameId'
      preLoaderRoute: typeof GamePreviewGameIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team/$teamId/lineup': {
      id: '/team/$teamId/lineup'
      path: '/lineup'
      fullPath: '/team/$teamId/lineup'
      preLoaderRoute: typeof TeamTeamIdLineupRouteImport
      parentRoute: typeof TeamTeamIdRoute
    }
    '/player/skater/$id': {
      id: '/player/skater/$id'
      path: '/player/skater/$id'
      fullPath: '/player/skater/$id'
      preLoaderRoute: typeof PlayerSkaterIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/player/goalie/$id': {
      id: '/player/goalie/$id'
      path: '/player/goalie/$id'
      fullPath: '/player/goalie/$id'
      preLoaderRoute: typeof PlayerGoalieIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface TeamTeamIdRouteChildren {
  TeamTeamIdLineupRoute: typeof TeamTeamIdLineupRoute
}

const TeamTeamIdRouteChildren: TeamTeamIdRouteChildren = {
  TeamTeamIdLineupRoute: TeamTeamIdLineupRoute,
}

const TeamTeamIdRouteWithChildren = TeamTeamIdRoute._addFileChildren(
  TeamTeamIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DevelopmentSummaryRoute: DevelopmentSummaryRoute,
  FreeAgentsRoute: FreeAgentsRoute,
  PlayoffsRoute: PlayoffsRoute,
  ScheduleRoute: ScheduleRoute,
  SeasonCompleteRoute: SeasonCompleteRoute,
  StandingsRoute: StandingsRoute,
  StatsRoute: StatsRoute,
  TradesRoute: TradesRoute,
  GamePreviewGameIdRoute: GamePreviewGameIdRoute,
  GameGameIdRoute: GameGameIdRoute,
  ManagerChooseTeamRoute: ManagerChooseTeamRoute,
  ManagerCreateRoute: ManagerCreateRoute,
  TeamTeamIdRoute: TeamTeamIdRouteWithChildren,
  ManagerIndexRoute: ManagerIndexRoute,
  PlayerGoalieIdRoute: PlayerGoalieIdRoute,
  PlayerSkaterIdRoute: PlayerSkaterIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
